# Generated by Django 4.2.1 on 2023-05-20 17:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actualite',
            fields=[
                ('id_actu', models.IntegerField(primary_key=True, serialize=False)),
                ('id_circuit', models.IntegerField()),
                ('titre_actu', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Artisanat',
            fields=[
                ('id_artisanat', models.IntegerField(primary_key=True, serialize=False)),
                ('nom_artisanat', models.CharField(max_length=40)),
                ('image_artisanat', models.ImageField(upload_to='artisanat_images')),
                ('date_modification', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Chambre',
            fields=[
                ('num_chambre', models.IntegerField(primary_key=True, serialize=False)),
                ('id_hotel', models.IntegerField()),
                ('type_chambre', models.CharField(max_length=20)),
                ('prix_chambre', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='CircuitVoyage',
            fields=[
                ('id_circuit', models.IntegerField(primary_key=True, serialize=False)),
                ('ville_depart', models.CharField(max_length=30)),
                ('ville_arrivee', models.CharField(max_length=30)),
                ('trajet', models.TextField()),
                ('date_depart', models.DateTimeField()),
                ('duree', models.IntegerField()),
                ('image_cover', models.ImageField(upload_to='circuit_images')),
                ('image_trajet', models.ImageField(upload_to='circuit_images')),
                ('prix', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fin_reservation', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id_client', models.IntegerField(primary_key=True, serialize=False)),
                ('nom_client', models.CharField(max_length=30)),
                ('prenom_client', models.CharField(max_length=30)),
                ('email_client', models.CharField(max_length=60)),
                ('login_client', models.CharField(max_length=40)),
                ('password_client', models.CharField(max_length=40)),
                ('date_inscription', models.DateTimeField()),
                ('code', models.IntegerField()),
                ('status', models.CharField(max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id_dest', models.IntegerField(primary_key=True, serialize=False)),
                ('nom_dest', models.CharField(max_length=30)),
                ('ville_dest', models.CharField(max_length=20)),
                ('province', models.CharField(max_length=30)),
                ('image_dest1', models.ImageField(upload_to='destination_images')),
                ('image_dest2', models.ImageField(upload_to='destination_images')),
                ('image_dest3', models.ImageField(upload_to='destination_images')),
                ('localisation_dest', models.CharField(max_length=255)),
                ('carte_dest', models.TextField()),
                ('description_dest', models.TextField()),
                ('date_modification', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id_hotel', models.IntegerField(primary_key=True, serialize=False)),
                ('nom_hot', models.CharField(max_length=30)),
                ('ville_hot', models.CharField(max_length=20)),
                ('province', models.CharField(max_length=30)),
                ('image_hot1', models.ImageField(upload_to='hotel_images')),
                ('image_hot2', models.ImageField(upload_to='hotel_images')),
                ('image_hot3', models.ImageField(upload_to='hotel_images')),
                ('localisation_hot', models.CharField(max_length=255)),
                ('carte_hot', models.TextField()),
                ('nbChambres', models.IntegerField()),
                ('classe_hot', models.IntegerField()),
                ('date_modification', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Materiels',
            fields=[
                ('id_materiel', models.IntegerField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=40)),
                ('image1', models.ImageField(upload_to='materiel_images')),
                ('image2', models.ImageField(upload_to='materiel_images')),
                ('image3', models.ImageField(upload_to='materiel_images')),
                ('prix', models.DecimalField(decimal_places=0, max_digits=10)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id_msg', models.IntegerField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField(default=models.DateTimeField(auto_now_add=True))),
                ('nom_redacteur', models.CharField(max_length=40)),
                ('email_redacteur', models.CharField(max_length=60)),
                ('sujet', models.CharField(max_length=60)),
                ('message', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Moussem',
            fields=[
                ('id_moussem', models.IntegerField(primary_key=True, serialize=False)),
                ('nom_moussem', models.CharField(max_length=30)),
                ('ville_moussem', models.CharField(max_length=20)),
                ('image_moussem1', models.ImageField(upload_to='moussem_images')),
                ('image_moussem2', models.ImageField(upload_to='moussem_images')),
                ('image_moussem3', models.ImageField(upload_to='moussem_images')),
                ('description_moussem', models.TextField()),
                ('date_modification', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Plat',
            fields=[
                ('id_plat', models.IntegerField(primary_key=True, serialize=False)),
                ('nom_plat', models.CharField(max_length=30)),
                ('image_plat1', models.ImageField(upload_to='plat_images')),
                ('image_plat2', models.ImageField(upload_to='plat_images')),
                ('image_plat3', models.ImageField(upload_to='plat_images')),
                ('description_plat', models.TextField()),
                ('date_modification', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id_rest', models.IntegerField(primary_key=True, serialize=False)),
                ('nom_rest', models.CharField(max_length=30)),
                ('ville_rest', models.CharField(max_length=30)),
                ('province', models.CharField(max_length=20)),
                ('image_rest1', models.ImageField(upload_to='restaurant_images')),
                ('image_rest2', models.ImageField(upload_to='restaurant_images')),
                ('image_rest3', models.ImageField(upload_to='restaurant_images')),
                ('localisation_rest', models.CharField(max_length=255)),
                ('carte_rest', models.TextField()),
                ('description_rest', models.TextField()),
                ('date_modification', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id_res', models.IntegerField(primary_key=True, serialize=False)),
                ('tel_client', models.IntegerField()),
                ('type_chambre', models.CharField(max_length=25)),
                ('nb_personnes', models.IntegerField(null=True)),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('prix', models.DecimalField(decimal_places=0, max_digits=10)),
                ('type_paiement', models.CharField(max_length=30)),
                ('date_res', models.DateTimeField()),
                ('status', models.CharField(max_length=20)),
                ('id_client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.client')),
                ('id_hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.hotel')),
            ],
        ),
    ]
