# Generated by Django 4.2.1 on 2023-05-22 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_admin_human_reservationmateriel_reservationvoyage_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='actualite',
            table='actualite',
        ),
        migrations.AlterModelTable(
            name='artisanat',
            table='artisanat',
        ),
        migrations.AlterModelTable(
            name='chambre',
            table='chambre',
        ),
        migrations.AlterModelTable(
            name='circuitvoyage',
            table='circuit_voyage',
        ),
        migrations.AlterModelTable(
            name='client',
            table='client',
        ),
        migrations.AlterModelTable(
            name='destination',
            table='destination',
        ),
        migrations.AlterModelTable(
            name='hotel',
            table='hotel',
        ),
        migrations.AlterModelTable(
            name='materiels',
            table='materiels',
        ),
        migrations.AlterModelTable(
            name='messages',
            table='messages',
        ),
        migrations.AlterModelTable(
            name='moussem',
            table='moussem',
        ),
        migrations.AlterModelTable(
            name='plat',
            table='plat',
        ),
        migrations.AlterModelTable(
            name='reservation',
            table='reservation',
        ),
        migrations.AlterModelTable(
            name='restaurant',
            table='restaurant',
        ),
    ]
