# Generated by Django 4.2.2 on 2023-06-15 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_delete_human'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.IntegerField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.IntegerField()),
                ('is_active', models.IntegerField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.PositiveSmallIntegerField()),
                ('change_message', models.TextField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Human',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, max_length=10, null=True)),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
                ('address', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'db_table': 'human',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MyappActualite',
            fields=[
                ('id_actu', models.IntegerField(primary_key=True, serialize=False)),
                ('id_circuit', models.IntegerField()),
                ('titre_actu', models.CharField(max_length=40)),
            ],
            options={
                'db_table': 'myapp_actualite',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MyappArtisanat',
            fields=[
                ('id_artisanat', models.IntegerField(primary_key=True, serialize=False)),
                ('nom_artisanat', models.CharField(max_length=40)),
                ('image_artisanat', models.CharField(max_length=100)),
                ('date_modification', models.DateTimeField()),
            ],
            options={
                'db_table': 'myapp_artisanat',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MyappChambre',
            fields=[
                ('num_chambre', models.IntegerField(primary_key=True, serialize=False)),
                ('id_hotel', models.IntegerField()),
                ('type_chambre', models.CharField(max_length=20)),
                ('prix_chambre', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'myapp_chambre',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MyappCircuitvoyage',
            fields=[
                ('id_circuit', models.IntegerField(primary_key=True, serialize=False)),
                ('ville_depart', models.CharField(max_length=30)),
                ('ville_arrivee', models.CharField(max_length=30)),
                ('trajet', models.TextField()),
                ('date_depart', models.DateTimeField()),
                ('duree', models.IntegerField()),
                ('image_cover', models.CharField(max_length=100)),
                ('image_trajet', models.CharField(max_length=100)),
                ('prix', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fin_reservation', models.DateField()),
            ],
            options={
                'db_table': 'myapp_circuitvoyage',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MyappClient',
            fields=[
                ('id_client', models.IntegerField(primary_key=True, serialize=False)),
                ('nom_client', models.CharField(max_length=30)),
                ('prenom_client', models.CharField(max_length=30)),
                ('email_client', models.CharField(max_length=60)),
                ('login_client', models.CharField(max_length=40)),
                ('password_client', models.CharField(max_length=40)),
                ('date_inscription', models.DateTimeField()),
                ('code', models.IntegerField()),
                ('status', models.CharField(max_length=12)),
            ],
            options={
                'db_table': 'myapp_client',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MyappDestination',
            fields=[
                ('id_dest', models.IntegerField(primary_key=True, serialize=False)),
                ('nom_dest', models.CharField(max_length=30)),
                ('ville_dest', models.CharField(max_length=20)),
                ('province', models.CharField(max_length=30)),
                ('image_dest1', models.CharField(max_length=100)),
                ('image_dest2', models.CharField(max_length=100)),
                ('image_dest3', models.CharField(max_length=100)),
                ('localisation_dest', models.CharField(max_length=255)),
                ('carte_dest', models.TextField()),
                ('description_dest', models.TextField()),
                ('date_modification', models.DateTimeField()),
            ],
            options={
                'db_table': 'myapp_destination',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MyappHotel',
            fields=[
                ('id_hotel', models.IntegerField(primary_key=True, serialize=False)),
                ('nom_hot', models.CharField(max_length=30)),
                ('ville_hot', models.CharField(max_length=20)),
                ('province', models.CharField(max_length=30)),
                ('image_hot1', models.CharField(max_length=100)),
                ('image_hot2', models.CharField(max_length=100)),
                ('image_hot3', models.CharField(max_length=100)),
                ('localisation_hot', models.CharField(max_length=255)),
                ('carte_hot', models.TextField()),
                ('nbchambres', models.IntegerField(db_column='nbChambres')),
                ('classe_hot', models.IntegerField()),
                ('date_modification', models.DateTimeField()),
            ],
            options={
                'db_table': 'myapp_hotel',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MyappMateriels',
            fields=[
                ('id_materiel', models.IntegerField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=40)),
                ('image1', models.CharField(max_length=100)),
                ('image2', models.CharField(max_length=100)),
                ('image3', models.CharField(max_length=100)),
                ('prix', models.DecimalField(decimal_places=0, max_digits=10)),
                ('description', models.TextField()),
            ],
            options={
                'db_table': 'myapp_materiels',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MyappMessages',
            fields=[
                ('id_msg', models.IntegerField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField()),
                ('nom_redacteur', models.CharField(max_length=40)),
                ('email_redacteur', models.CharField(max_length=60)),
                ('sujet', models.CharField(max_length=60)),
                ('message', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'myapp_messages',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MyappMoussem',
            fields=[
                ('id_moussem', models.IntegerField(primary_key=True, serialize=False)),
                ('nom_moussem', models.CharField(max_length=30)),
                ('ville_moussem', models.CharField(max_length=20)),
                ('image_moussem1', models.CharField(max_length=100)),
                ('image_moussem2', models.CharField(max_length=100)),
                ('image_moussem3', models.CharField(max_length=100)),
                ('description_moussem', models.TextField()),
                ('date_modification', models.DateTimeField()),
            ],
            options={
                'db_table': 'myapp_moussem',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MyappPlat',
            fields=[
                ('id_plat', models.IntegerField(primary_key=True, serialize=False)),
                ('nom_plat', models.CharField(max_length=30)),
                ('image_plat1', models.CharField(max_length=100)),
                ('image_plat2', models.CharField(max_length=100)),
                ('image_plat3', models.CharField(max_length=100)),
                ('description_plat', models.TextField()),
                ('date_modification', models.DateTimeField()),
            ],
            options={
                'db_table': 'myapp_plat',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MyappReservation',
            fields=[
                ('id_res', models.IntegerField(primary_key=True, serialize=False)),
                ('tel_client', models.IntegerField()),
                ('type_chambre', models.CharField(max_length=25)),
                ('nb_personnes', models.IntegerField(blank=True, null=True)),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('prix', models.DecimalField(decimal_places=0, max_digits=10)),
                ('type_paiement', models.CharField(max_length=30)),
                ('date_res', models.DateTimeField()),
                ('status', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'myapp_reservation',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MyappRestaurant',
            fields=[
                ('id_rest', models.IntegerField(primary_key=True, serialize=False)),
                ('nom_rest', models.CharField(max_length=30)),
                ('ville_rest', models.CharField(max_length=30)),
                ('province', models.CharField(max_length=20)),
                ('image_rest1', models.CharField(max_length=100)),
                ('image_rest2', models.CharField(max_length=100)),
                ('image_rest3', models.CharField(max_length=100)),
                ('localisation_rest', models.CharField(max_length=255)),
                ('carte_rest', models.TextField()),
                ('description_rest', models.TextField()),
                ('date_modification', models.DateTimeField()),
            ],
            options={
                'db_table': 'myapp_restaurant',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Ville',
            fields=[
                ('ville_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('ville_name', models.CharField(max_length=255)),
                ('population', models.IntegerField(blank=True, null=True)),
                ('area_km2', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('country', models.CharField(blank=True, max_length=255, null=True)),
                ('region', models.CharField(blank=True, max_length=255, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('image1', models.CharField(blank=True, max_length=255, null=True)),
                ('image2', models.CharField(blank=True, max_length=255, null=True)),
                ('image3', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'ville',
                'managed': False,
            },
        ),
    ]
